### ISSUE TITLE
README.md - Broken Link to Design Patterns in Java

### ISSUE THREAD

**Issue by thesammiller** [douglascraigschmidt/LiveLessons#17]
The link to Design Patterns in Java is broken due to a minor typo.

http://www.dre.vanderbilt.edu/~schmidt/LiveLessons/DPwJava/
should be
http://www.dre.vanderbilt.edu/~schmidt/LiveLessons/DPiJava/

where an **i** replaces the **w** in **DPwJava**

**Comment by douglascraigschmidt** [comment]
Thanks Sam, I’ve fixed this!!

Doug
