### ISSUE TITLE
import sun.plugin.liveconnect.SecurityContextHelper;

### ISSUE THREAD

**Issue by americanstone** [douglascraigschmidt/LiveLessons#8]
not able to find this class in the project. so it's not able to compile the project at all. since it's not referenced anywhere I removed it and it starts working.

**Comment by douglascraigschmidt** [comment]
Which project are you referring to?
Thanks,
Doug

**Comment by americanstone** [comment]
Hey, it is LiveLessons SearchStreamGang project. Supposing I have to download java-plugin*.jar file for this project? 
~/Projects/LiveLessons/SearchStreamGang (master) 🍺  $git diff
diff --git a/SearchStreamGang/src/main/java/livelessons/streamgangs/SearchWithRxJavaInputs.java b/SearchStreamGang/src/main/java/livelessons/streamgangs/SearchWithRxJavaInputs.java
index 6e5ea0a..96e88fa 100644
--- a/SearchStreamGang/src/main/java/livelessons/streamgangs/SearchWithRxJavaInputs.java
+++ b/SearchStreamGang/src/main/java/livelessons/streamgangs/SearchWithRxJavaInputs.java
@@ -1,6 +1,6 @@
 package livelessons.streamgangs;

-import sun.plugin.liveconnect.SecurityContextHelper;
+//import sun.plugin.liveconnect.SecurityContextHelper;

 import java.util.ArrayList;
 import java.util.Iterator;

**Comment by douglascraigschmidt** [comment]
Thanks - I've applied this fix and pushed it to github!

Doug
